COPRS/infrastructure

README.md, platform/inventory/sample/group_vars/all/kubespray.yaml
=> fix(kubernetes): PSP prevent masters to join the cluster

roles/image/tasks/main.yaml, roles/image/templates/base_image.j2
Fix COPRS/rs-issues#218
Fixing image creation role with correct paths for scripts and output destination
=> fix[deployment]: Fix image creation with correct paths for scripts and output destination

apps/finops-object-storage-exporter/config.yaml, apps/finops-object-storage-exporter/values.yaml, apps/finops-resources-exporter/config.yaml, apps/finops-resources-exporter/values.yaml, inventory/sample/group_vars/gateway/app_installer.yaml
Implements  [rs-issues#175](https://github.com/COPRS/rs-issues/issues/175).
=> feat[monitoring]: add finops metrics exporters

apps/40-rook-ceph/kustomization.yaml, apps/50-rook-ceph-cluster/kustomization.yaml, apps/50-rook-ceph-cluster/patch.yaml, apps/50-rook-ceph-cluster/values.yaml, apps/70-cert-manager/values.yaml, apps/apisix/kustomization.yaml, apps/apisix/routes/apisix-apisixroute.yaml, apps/apisix/routes/infra-apisixroute.yaml, apps/apisix/routes/linkerd-apisixroute.yaml, apps/apisix/routes/monitoring-apisixroute.yaml, apps/apisix/routes/scdf-apisixroute.yaml, apps/apisix/routes/security-apisixroute.yaml, apps/apisix/routes/sni-tls.yaml, apps/apisix/serviceMonitor.yaml, apps/apisix/values.yaml, apps/elasticsearch-processing/kustomization.yaml, apps/fluent-bit/kustomization.yaml, apps/fluentd/kustomization.yaml, apps/keycloak/kustomization.yaml, apps/loki/kustomization.yaml, apps/mongodb/kustomization.yaml, apps/openldap/kustomization.yaml, apps/postgresql/kustomization.yaml
This PR implements a new namespace distribution, in order to have more intelligible namespaces grouping related apps.
Related to https://github.com/coprs/rs-issues/issues/234
=> Feat: New namespaces distribution

apps/00-linkerd-cni/kustomization.yaml, apps/00-linkerd-cni/values.yaml, apps/10-linkerd/kustomization.yaml, apps/10-linkerd/trust-anchor-certificate/certificate-linkerdidentityissuer.yaml, apps/10-linkerd/trust-anchor-certificate/issuer-linkerdtrustanchor.yaml, apps/10-linkerd/trust-anchor-certificate/tls.crt, apps/10-linkerd/trust-anchor-certificate/tls.key, apps/10-linkerd/values.yaml, apps/10-linkerd/webhook-certificates/certificate-linkerdpolicyvalidator.yaml, apps/10-linkerd/webhook-certificates/certificate-linkerdproxyinjector.yaml, apps/10-linkerd/webhook-certificates/certificate-linkerdspvalidator.yaml, apps/10-linkerd/webhook-certificates/issuer-webhookissuer.yaml, apps/10-linkerd/webhook-certificates/tls.crt, apps/10-linkerd/webhook-certificates/tls.key, apps/30-linkerd-viz/certificate-linkerdtap.yaml, apps/30-linkerd-viz/certificate-linkerdtapinjector.yaml, apps/30-linkerd-viz/kustomization.yaml, apps/30-linkerd-viz/linkerd-control-plane-metrics.yaml, apps/30-linkerd-viz/linkerd-proxy-metrics.yaml, apps/30-linkerd-viz/values.yaml, inventory/sample/group_vars/gateway/app_vars.yaml
This PR implements Linkerd automatic TLS credentials rotation and update linkerd to respect the new namespace distribution.
Related to COPRS/rs-issues#234
=> feat: linkerd tls certificate rotation

apps/70-kafka-operator/Kafka/kafka-cluster.yaml, apps/80-elasticsearch-processing/backup-config-job.yaml, apps/80-elasticsearch-processing/elasticsearch.yaml, apps/80-elasticsearch-security/backup-config-job.yaml, apps/80-elasticsearch-security/elasticsearch.yaml, apps/fluentd/custom_plugins/out_loki.rb, apps/fluentd/values.yaml, apps/graylog/values.yaml, roles/rs-defaults/defaults/main.yaml
This PR reports fixes from v3 integration and some other improvements, including:
- elasticsearch cluster sizing
- official fluentd loki output plugin update
- kafka scale up and affinities
Related to https://github.com/COPRS/rs-issues/issues/234
=> Feat: report v3 fixes

apps/70-elasticsearch-processing/apisixroute-kibana.yaml, apps/70-elasticsearch-processing/elasticsearch.yaml, apps/70-elasticsearch-processing/filerealm-secret.yaml, apps/70-elasticsearch-processing/grafanadatasource.yaml, apps/70-elasticsearch-processing/kibana.yaml, apps/70-elasticsearch-processing/kustomization.yaml, apps/70-elasticsearch-processing/repository-config-job.yaml, apps/grafana/kustomization.yaml
This PR fixes a merge issue related to es grafana datasource location
=> Fix merge issue with es grafana datasource location

apps/apisix/additional_resources/monitoring-apisixroute.yaml
Small fix for https://github.com/coprs/rs-issues/issues/281
=> fix: Allow all methods for grafana apisixroute

doc/how-to/Databases backups.md
Fixes the backup and restore documentation to solve issue COPRS/rs-issues#352.
=> fix: correction to backup doc

apps/00-keda-crds/crd-triggerauthentications.keda.sh.yaml, apps/00-keda-crds/kustomization.yaml
Fix issue https://github.com/COPRS/rs-issues/issues/374
=> fix: Add missing keda CRD

doc/how-to/Nodes.md
- add more information about node sizing, additional storage, references to the safescale's documentation
- add missing part about security components installation for a newly created node
=> doc: add more information about storage and security components

roles/rs-addon/tasks/main.yaml
Fixes COPRS/rs-issues#394
- add conditional check for additional_resources directory content lookup
=> fix: add conditional check for additional_resources directory content lookup

README.md, apps/00-apisix-crds/crd-apisixclusterconfigs.yaml, apps/00-apisix-crds/crd-apisixconsumers.yaml, apps/00-apisix-crds/crd-apisixpluginconfigs.yaml, apps/00-apisix-crds/crd-apisixroutes.yaml, apps/00-apisix-crds/crd-apisixtlses.yaml, apps/00-apisix-crds/crd-apisixupstreams.yaml, apps/00-apisix-crds/kustomization.yaml, apps/30-linkerd-viz/apisixroute.yaml, apps/70-elasticsearch-processing/apisixroute-kibana.yaml, apps/70-elasticsearch-security/apisixroute-kibana.yaml, apps/70-thanos/apisixroute.yaml, apps/80-prometheus-stack/apisixroute.yaml, apps/apisix/apisixroute.yaml, apps/apisix/kustomization.yaml, apps/apisix/values.yaml, apps/grafana/apisixroute.yaml, apps/graylog/apisixroute.yaml, apps/keycloak/apisixroute.yaml, apps/kubectl-oidc/apisixroute.yaml, apps/spring-cloud-dataflow/apisixroute.yaml
Fix: https://github.com/coprs/rs-issues/issues/277
- Bump Apisix chart to 0.9.3
- Bump Apisix Ingress Controller to 1.4.1
=> Upgrade apisix chart

apps/50-rook-ceph-cluster/apisixroute.yaml, apps/keycloak/custom-realm.json, inventory/sample/host_vars/setup/apps/ceph.yaml
This PR fixes a small typo due to ansible variables formatting
=> fix: ceph typos

README.md, apps/autoscaling/rs-infra-scaler.yaml, apps/graylog/values.yaml, scaler/Dockerfile, scaler/Makefile, scaler/infra_shell_client.go
This PR includes three small fixes:
- graylog values wrong identation
- scaler not using latest release branch in docker build
- golang string sorting causing issue on some clusters
=> fix: scaler hotfix1

Makefile, apps/autoscaling/cluster-autoscaler.yaml, roles/safescale/create-cluster/tasks/create-nodegroup.yaml, roles/safescale/delete-machines/tasks/delete-machine.yaml, roles/safescale/expand-nodegroup/tasks/main.yaml, scaler/Dockerfile, scaler/main.go, scaler/safescaled.Dockerfile
This PR includes some small fixes on the build of scaling image and a bit  of refactor on the ansible roles.
=> fix: build fixes and ansible refactor

.github/workflows/docker-ci-scaler.yml
- Update variable usage
- Update security scan
=> fix(ci): docker workflow

roles/security/suricata/files/logrotate, roles/security/suricata/tasks/install.yaml
This PR fixes https://github.com/COPRS/rs-issues/issues/390
=> feat: set up suricata log rotation

apps/80-prometheus-stack/values.yaml
Fixes issue COPRS/rs-issues#516
- Add NoSchedule tolerations to node-exporter
=> fix: add NoSchedule tolerations to node-exporter

apps/grafana/grafana.yaml, apps/keycloak/custom-realm.json
Fix COPRS/rs-issues#341 - invalid url when logout on grafana
- Changes keycloak realm file
- Changes  grafana values file
=> fix: grafana logout url

NOTICE.md, apps/00-grafana-operator-crds/crd-grafanadashboards.yaml, apps/00-grafana-operator-crds/crd-grafanadatasources.yaml, apps/00-grafana-operator-crds/crd-grafanafolders.yaml, apps/00-grafana-operator-crds/crd-grafanas.yaml, apps/00-grafana-operator-crds/kustomization.yaml, apps/60-grafana-operator/deployment.yaml, apps/60-grafana-operator/rbac.yaml, apps/grafana/grafana.yaml, inventory/sample/host_vars/setup/apps/grafana.yaml
Improvements:
- assign GrafanaAdmin role instead of Admin (closes https://github.com/COPRS/rs-issues/issues/356)
Features:
- allow deployment of custom remote and unsigned Grafana plugins (allows integrating https://github.com/COPRS/rs-issues/issues/486)
Improvements:
- update Grafana operator to 4.8.0 and Grafana to 9.3.0 (both latest)
=> feat: update grafana and some features

NOTICE.md, apps/spring-cloud-dataflow/kustomization.yaml, apps/spring-cloud-dataflow/values.yaml
This PR updates SCDF chart and image to their latest versions.
Fixes https://github.com/coprs/rs-issues/issues/716
=> feat: update SCDF to 2.9.6

NOTICE.md, README.md
Remove ESA Copyright in README.md and NOTICE.md files
=> Qla remove esa copyright

README.md
=> Fix path in README.md

docs/architecture/README.md, docs/installation_manual/README.md, docs/interfaces/README.md, docs/user_manuals/README.md
Homogenization of the titles of the documentation
=> Vgava ads docstitles

CONFIG.md, NOTICE.md, docs/architecture/README.md, docs/user_manuals/how-to/Security.md
Replace COTS with FOSS by Airbus request
=> Replace COTS with FOSS
